---
title: "Albacore Diet Synthesis Rarefaction"
author: "Natasha Hardy"
date: "20/10/2021"
output: html_document
---

# Biological and trait diversity in diets of a highly migratory predator

```{r setup, include=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r Load Workspace, message=FALSE}

#R documentation
library(pander)
# general
library(tidyverse)
library(readxl)
library(readr)
library(plyr)
library(dplyr)
library(devtools)
library(here)
"%notin%" = Negate('%in%')
here::here()

#Graphics
library(ggplot2)
library(viridis)
library(RColorBrewer)
library(wesanderson)

#Biodiversity
library(BiodiversityR)
library(vegan)
# From GitHub
#install_github("MoBiodiv/mobr")
library(mobr)
#devtools::install_github('bbc/bbplot')
#library(bbplot)
```

## Rarefaction data

## Rarefaction curves for known taxa:

```{r Rarefaction curves data}
#Data -- using total diet data
alb_global_dietpa = read.csv(here("data/output_data/alb_global_wide_dietpa.csv"), 
          check.names = FALSE) %>%
  group_by(OceanBasin) %>%
  arrange(YearEnd)

## Albacore prey species P/A data
# data
PreyPAdata = as.data.frame(alb_global_dietpa[,10:ncol(alb_global_dietpa)])
PreyPAsite = as.data.frame(alb_global_dietpa[,c(1:5)])

PreyPAsite$YearEnd = as.integer(PreyPAsite$YearEnd)
PreyPAsite$StudyID = as.factor(PreyPAsite$StudyID)
PreyPAsite$OceanBasin = as.factor(PreyPAsite$OceanBasin)

str(PreyPAdata)
str(PreyPAsite)

rownames(PreyPAsite) = rownames(PreyPAdata)
check.datasets(PreyPAdata, PreyPAsite) #ensure that the sites of the community dataset are the same sites as those from the environmental dataset --> something that is assumed to be the case for the BiodiversityR and vegan packages.


write.csv(PreyPAsite, here("data/output_data/alb_global_rarefactiondata.csv"), row.names = FALSE)

```

```{r Rarefaction curves 2}

# number of species and the factor that I want to group them by
SpO <- specnumber(PreyPAdata, PreyPAsite$OceanBasin)
SpO

# Acummresult function

#Produces average species accumulation curve
Alb.accum <- accumresult(PreyPAdata, y=PreyPAsite$OceanBasin, method='exact', conditioned=TRUE)
str(Alb.accum)
accumplot(Alb.accum)

#Produces cumulative species curves
Alb.accum2 <- accumresult(PreyPAdata, y=PreyPAsite$OceanBasin, method='collector', conditioned=TRUE)
str(Alb.accum2)
accumplot(Alb.accum2)


#Produces average species accumulation curve

Plot <- accumcomp(PreyPAdata, y=PreyPAsite, factor='OceanBasin', scale = 'YearEnd', method='exact', conditioned=TRUE, plotit=TRUE) #scale = 'YearEnd'
str(Plot)
Plot.long <- accumcomp.long(Plot)
str(Plot.long)

#Plot.long.covar = Plot.long %>%
#  rename(OceanBasin = Grouping) %>%
#  left_join(PreyPAsite, by = "OceanBasin")

#Produces cumulative species curves
Plot2 <- accumcomp(PreyPAdata, y=PreyPAsite, factor='OceanBasin', scale = 'YearEnd', method='collector', conditioned=TRUE, plotit=TRUE)
str(Plot2)
Plot2.long <- accumcomp.long(Plot2)
str(Plot2.long)
# save and export the accumcomp data in order to add SW back in with just the one point

# Did this for first and second Plot output for accumcomp function.
write.csv(Plot.long, here("data/output_data/accum_plot.csv"), row.names = FALSE)
accum.data <- read.csv(here("data/output_data/accum_plot.csv"))
View(accum.data)

write.csv(Plot2.long, here("data/output_data/accum2_plot.csv"), row.names = FALSE)
accum2.data <- read.csv(here("data/output_data/accum2_plot.csv"))
View(accum2.data)

```

```{r}

accum.long1$Year <- NA
groupings <- unique(accum.long1$Grouping)
 
for (g in 1:length(groupings) {
group <- groupings[g]
# assuming Grouping was based on variable Region of the env.data
accum.long1[accum.long1$Grouping == group, “Year”] <- env.data[env.data$Region == group, “Year”]
}

```

```{r rarefaction graphs}

levels(as.factor(accum.data$Grouping))

accum.data$Grouping <- factor(accum.data$Grouping, levels = c("Mediterranean", "N Atlantic",
                                                        "S Atlantic", "Indian",
                                                        "N Pacific", "S Pacific"))

Accum.plot <- ggplot(data = accum.data, aes(y=Richness, x=Sites, colour=Grouping)) +
  geom_point(size=2) +
  geom_line(size=1.5) + 
  theme_classic() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))+
  theme(axis.title=element_text(size=18)) +
  theme(axis.text=element_text(size=18)) +
  theme(legend.text=element_text(size=18)) +
  theme(legend.title=element_text(size=18)) +
  labs(x="Years sampled", y="Species cumulative richness")+
  scale_colour_manual(values=wes_palette("Zissou1", 7, type="continuous"), name="Ocean Basin")+
  geom_errorbar(data = accum.data, aes(ymin=Richness-SD, ymax=Richness+SD), width=.2)
Accum.plot

ggsave(here("outputs_figures/accum.plot1.jpeg"), plot=Accum.plot, height = 8, width = 12, dpi = 300)

##Second plot
str(accum2.data)
levels(as.factor(accum2.data$Grouping))
accum2.data$Grouping <- factor(accum2.data$Grouping, levels = c("Mediterranean", "N Atlantic",
                                                        "S Atlantic", "Indian",
                                                        "N Pacific", "S Pacific"))

Accum.plot2 <- ggplot(data = accum2.data, aes(y=Richness, x=Sites, colour=Grouping)) +
  geom_point(size=2) +
  geom_line(size=1.5) + 
  theme_classic() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))+
  #geom_text(aes(x=Year, label=Stomachs), size=4, hjust=0.5, col="black") +
  #geom_text_repel(data = accum.data2, aes(x=Year, label=Stomachs),
  #                nudge_x = -10, nudge_y = 10) +
  theme(axis.title=element_text(size=18)) +
  theme(axis.text=element_text(size=18)) +
  theme(legend.text=element_text(size=18)) +
  theme(legend.title=element_text(size=18)) +
  labs(x="Years sampled", y="Species cumulative richness")+
  scale_colour_manual(values=wes_palette("Zissou1", 7, type="continuous"), name="Ocean Basin")
Accum.plot2

ggsave(here("outputs_figures/accum.plot2.jpeg"), plot=Accum.plot2, height = 8, width = 12, dpi = 300)


#Note no error bar for pure accumulation plot

```