---
title: "Bar Graph Troubleshoot"
author: "Natasha Hardy"
date: '2022-06-15'
output: html_document
---

## About

To produce graphical illustrations of global albacore diet composition in relation to prey clusters/guilds and relative importance of prey trait guilds.

## Workspace

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages to load}
library(here)
"%notin%" = Negate('%in%')
here::here()
library(tidyverse)
library(readxl)
library(readr)
library(plyr)
library(dplyr)
library(vegan)
library(mvabund)
library(ggplot2)
library(viridis)
#library(RColorBrewer)
#library(ggh4x)
#library(wesanderson)

```

## DF for FO index of relative importance

```{r Create df for range graph}

#This df was created using the following math
#index_alb_diet_clust = alb_diet_clust %>%
#  group_by(StudyID, rep_ID, YearEnd, OceanBasin, prob.clust.num) %>%
#  dplyr::summarize(clustFO = sum(pFOuse, na.rm=TRUE)) 

#totals_alb_diet_clust = alb_diet_clust %>%
#  group_by(StudyID, rep_ID, YearEnd, OceanBasin) %>%
#  dplyr::summarize(totalFO = sum(pFOuse, na.rm=TRUE)) 

#index_alb_diet_clust_data = index_alb_diet_clust %>%
#  left_join(totals_alb_diet_clust) %>%
#  mutate(relFO = clustFO/totalFO)

index_alb_diet_clust_data = read.csv(here::here("data/output_data/index_alb_diet_clust_data.csv"))

```

## Graph

Match the colour palette for clusters in these and other graphs in the MS.

```{r Colour palette for cluster graphs}

fig3.pal <- c("#00496F", "#59A082", "#0A718F", 
              "#EDA417", "#EDD746", 
              "#E7720B", "#DD4124")
library(scales)
show_col(fig3.pal)

```

```{r Try stacked bar chart}

index_cluster_bar = index_alb_diet_clust_data %>%
  #filter(pFOuse > 5) %>%
  ggplot() +
  geom_bar(data = index_alb_diet_clust_data, 
             aes(y=relFO, x=YearEnd, #group=rep_ID, 
                 fill=prob.clust.num),
             width = 1, stat = "identity") + #, position = "jitter", , position="identity"
  #geom_jitter(position = position_jitter(width = 0.1, height = 0.1))+
  theme(panel.grid.major = element_blank(),
        axis.title=element_text(size=24),
        axis.text=element_text(size=24),
        legend.text=element_text(size=24),
        legend.title=element_text(size=24),
        legend.position = "top") +
  labs(x="Years sampled", y="Relative %FO")+
  scale_fill_manual(values=fig3.pal, name="Prey Trait Guilds") +
  facet_grid(OceanBasin~.)+ #, scales ="free"
  theme(strip.text = element_text(face="bold", size=rel(2)))
index_cluster_bar

```