---
title: "Extra"
author: "Natasha Hardy & Caitlin Morgenson"
date: "26/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## LOAD IN CLEAN DATASETS HERE

```{r LOAD prey_morph_sum}

prey_morph_sum = read.csv(here("/data/prey_morph_sum.csv")) %>%
  dplyr::select(-X)

```

```{r LOAD prey_qual_sum}
prey_qual_sum = read.csv(here("/data/prey_qual_sum.csv")) %>%
  dplyr::select(-X)

```

```{r LOAD alb_global}

#Reload data
alb_global = read.csv(here("data/alb_global_diet_total.csv")) %>%
  dplyr::select(-X)
unique(alb_global$StudyID) #26 papers in analyses

```

```{r LOAD alb_global_prob}

alb_global_prob = read.csv(here("data/alb_global_diet_prob.csv")) %>%
  dplyr::select(-X)

```


### Albacore prey trait db


```{r Prey traits adults - data extract}

prey_trait_adult = prey_trait %>%
  dplyr::filter(life_stage == "adult") %>% #currently df already split by age group
  dplyr::select(prey_class:prey_sp, vert_habitat, horz_habitat, diel_migrant, diel_migrant_cat, refuge, refuge_cat, season_migrant, season_cat, body_shape, l_max, phys_defense, transparent, col_disrupt, silver, countershade, gregarious_primary, trophic_level, fisheries_status) #select traits we want to analyse
  
str(prey_trait_adult) #Extracting 308 species and 18 variables
str(prey_trait)
```

### Prey size graphs

```{r PREY SIZE GRAPHS}

##Now we need cut offs for larva and juveniles maybe based either at class, order or family levels
## GRAPH THIS!

## Visualising raw values
### For larvae
prey_length_data %>% 
  filter(life_stage == "larva") %>%
  ggplot() +
  geom_boxplot(aes(x=prey_class, y=length_tl, fill=measure)) +
  #xlab("Ocean Basin") + ylab("Frequency of Occurance(%)") + 
  theme_classic() +
  scale_fill_viridis_d(option="D", begin = 1, end = 0.6, name = "Length")+
  theme(axis.title=element_text(size=20)) +
  theme(axis.text=element_text(size=20)) +
  theme(legend.text=element_text(size=20)) +
  theme(legend.title=element_text(size=20)) +
  theme(legend.position="top")

## Note:
#For crustaceans, there are very few that would be consumed as larvae, as their sizes are so small, there may be other ways to select a probable life stage.
#For cephalopods, appears to be group 1 ~ 4 cm, with median ~ 1.5-2 cm
#For fish, there is at least a group cut off < 4 cm, and 1st quartile ~ 2.5 cm, median ~ 3 cm.
## Need to calculate ratios

#Calculate mean?
### For juveniles
prey_length_data %>% 
  filter(life_stage == "juvenile") %>%
  ggplot() +
  geom_boxplot(aes(x=prey_class, y=length_tl, fill=measure)) +
  #xlab("Ocean Basin") + ylab("Frequency of Occurance(%)") + 
  theme_classic() +
  scale_fill_viridis_d(option="D", begin = 1, end = 0.6, name = "Length")+
  theme(axis.title=element_text(size=20)) +
  theme(axis.text=element_text(size=20)) +
  theme(legend.text=element_text(size=20)) +
  theme(legend.title=element_text(size=20)) +
  theme(legend.position="top")

## Note:
#For crustaceans ...
#For cephalopods ...
#For fish, where data missing use 1/3 adult size
summary(prey_length_wide$prey_class)

##Visualise using ratios
### For larvae
prey_length_wide %>% 
  dplyr::filter(prey_class %in% c("Actinopterygii", "Cephalopoda", "Malacostraca")) %>%
  ggplot() +
  geom_boxplot(aes(x=prey_class, y=larva_adult, fill=measure)) +
  #xlab("Ocean Basin") + ylab("Frequency of Occurance(%)") + 
  theme_classic() +
  scale_fill_viridis_d(option="D", begin = 1, end = 0.6, name = "Larval to adult length ratio")+
  theme(axis.title=element_text(size=20)) +
  theme(axis.text=element_text(size=20)) +
  theme(legend.text=element_text(size=20)) +
  theme(legend.title=element_text(size=20)) +
  theme(legend.position="top")
#Save output
ggsave(here("output_figures/diet_mvtraits/larva_adult_ratio.jpg"), width = 10, height = 5)

prey_length_wide %>% 
  dplyr::filter(prey_class %in% c("Actinopterygii", "Cephalopoda", "Malacostraca")) %>%
  ggplot() +
  geom_boxplot(aes(x=prey_class, y=juve_adult, fill=measure)) +
  #xlab("Ocean Basin") + ylab("Frequency of Occurance(%)") + 
  theme_classic() +
  scale_fill_viridis_d(option="D", begin = 1, end = 0.6, name = "Juvenile to adult length ratio")+
  theme(axis.title=element_text(size=20)) +
  theme(axis.text=element_text(size=20)) +
  theme(legend.text=element_text(size=20)) +
  theme(legend.title=element_text(size=20)) +
  theme(legend.position="top")

ggsave(here("output_figures/diet_mvtraits/juve_adult_ratio.jpg"), width = 10, height = 5)

```

## DATA SETS EXTRA

```{r ORDINAL Prey adult traits + morph + qual data}

#Ordinal traits

prey_adults_ord = prey_trait %>% 
  filter(prey_sp %in% prey_adults_merge$prey_sp,
         life_stage == "adult") %>%
  select(prey_class:prey_sp, life_stage, vert_primary_ordinal, horz_habitat_ordinal, diel_migrant, refuge, season_migrant, body_shape_ordinal, phys_defense, transparent, col_disrupt, silver, countershade, gregarious_ordinal)
  #left_join(prey_morph_sum, by="prey_sp") %>% 
  #left_join(prey_qual_sum, by="prey_sp") %>%
  #left_join(alb_global_ad_metrics, by="prey_sp")

#308 spp and ~17 traits
str(prey_adults_ord)

write.csv(prey_adults_ord, here("data/output_data/prey_adults_traits_ord.csv"))

```

```{r ORDINAL Prey probable traits + morph + qual data}

prey_probable_merge = read.csv(here("data/prey_probable_traits.csv"))

prey_prob_ord = prey_probable_merge %>% 
  select(prey_sp:life_stage) %>%
  left_join(prey_trait, by=c("prey_sp", "life_stage")) %>%
  select(prey_class:prey_family, prey_sp, life_stage, vert_primary_ordinal, horz_habitat_ordinal, diel_migrant, refuge, season_migrant, body_shape_ordinal, phys_defense, transparent, col_disrupt, silver, countershade, gregarious_ordinal)
  #left_join(prey_morph_sum, by="prey_sp") %>% 
  #left_join(prey_qual_sum, by="prey_sp") %>%
  #left_join(alb_global_ad_metrics, by="prey_sp")

dim(prey_adults_ord) #303 spp and ~17 traits

str(prey_prob_ord)

write.csv(prey_prob_ord, here("data/prey_prob_traits_ord.csv"))

```

```{r PROBABLE COVARS}

#Do we need probable life stage covars? Or can I subset?

```


## OLD DATASETS
### Phylograph Input files

```{r Prey traits - Phylographs draft}

#For phylo graphs
prey_traits_graphs = prey_trait_cats %>%
  select(prey_class:life_stage, vert_habitat, horz_habitat, diel_migrant, refuge, season_migrant, body_shape, phys_defense, transparent, col_disrupt, countershade, photophore_PA, gregarious_primary, trophic_level) %>% #Could add later for fisherman paper: IUCN_status, commercial, recreational
  dplyr::filter(life_stage == "adult") 
  #dplyr::filter( %in% ) %>% #c("no", "NA")
  #filter out everything but adult life_stage, filter out images that are use = "no"
  #drop_na(t_length, b_height, eye_diameter) %>% #filter out any NA's in the desired columns
  #mutate(b_shape_r = t_length/b_height, eye_body_r = eye_diameter/t_length)

str(prey_traits_graphs)
names(prey_trait_cats)
dim(prey_trait_cats) #809 rows for adult data


#FOR BASIC PHYLO TREE
my_prey = prey_traits_graphs %>%
  dplyr::select(prey_class:prey_sp)

write.csv(my_prey, "my_prey.csv")

```

```{r Prey traits - Clusters}

#Need the categorical traits for the cluster analyses
prey_traits_cats = prey_trait %>%
  dplyr::select(prey_class:prey_sp, life_stage, vert_habitat, horz_habitat, diel_migrant_cat, refuge_cat, season_cat, body_shape, defense_cat, gregarious_primary) %>% #Could add later for fisherman paper: IUCN_status, commercial, recreational
  dplyr::filter(life_stage == "adult") 
  #dplyr::filter( %in% ) %>% #c("no", "NA")
  #filter out everything but adult life_stage, filter out images that are use = "no"
  #drop_na(t_length, b_height, eye_diameter) %>% #filter out any NA's in the desired columns
  #mutate(b_shape_r = t_length/b_height, eye_body_r = eye_diameter/t_length)

write.csv(prey_traits_cats, "prey_traits_cats.csv")

glimpse(prey_traits_cats)
dim(prey_traits_cats) #809 rows for adult data
```


```{r Albacore diet data load for rarefaction curves}
getwd()

# need total unfiltered data for rarefaction curve
prey_total <- read.csv("prey_total.csv", header = TRUE)
head(prey_total)


# cleaned dataset, filtered for fish & cephalopods only, for include = yes, for FO > 0% and excluding NAs, for albacore adult diet.
prey_long <- read.csv("prey_long_clean.csv", header = TRUE)


```

## Plastics project rarefaction fig code

```{r plastics project rarefaction code}

#### RAREFACTION CURVE ----
## MAX'S RAREFACTION CURVE
## Cumulative unique entries in list of vectors

cum_unique <- function(l) {
  result <- integer(length(l))
  for (i in 1:length(l)) {
    result[i] <- length(unique(unlist(l[1:i])))
  }
  result
}

prey_rare <-  prey_total %>% 
  group_by(OceanBasinQ,YearSample) %>% 
  summarize(species = list(unique(PreySP))) #,
#            annual_N = sum(N)) %>% 
#  ungroup %>% 
#  mutate(cum_species = cum_unique(species),
#         cum_n = cumsum(annual_N),
#         cpue = cum_species / cum_n)

View(prey_rare)

d_rarefaction_ingest_only <-  d_full %>%  
  filter(prop_w_plastic > 0) %>% 
  group_by(publication_year) %>% 
  summarize(species = list(unique(binomial)),
            annual_N = sum(N)) %>% 
  ungroup %>% 
  mutate(cum_species = cum_unique(species),
         cum_n = cumsum(annual_N),
         cpue = cum_species / cum_n)

rarefaction_plot <- ggplot() +
  geom_line(data = d_rarefaction_all, aes(cum_n, cum_species), color = "dark blue") +
  geom_line(data = d_rarefaction_ingest_only, aes(cum_n, cum_species), color = "dark red") +
  geom_point(data = d_rarefaction_all, aes(cum_n, cum_species)) +
  geom_point(data = d_rarefaction_ingest_only, aes(cum_n, cum_species)) +
  geom_text_repel(data = d_rarefaction_all, 
                  aes(cum_n, cum_species, label = publication_year), 
                  nudge_x = -1500, nudge_y = 10,
                  segment.color = "black") +
  geom_text_repel(data = d_rarefaction_ingest_only, 
                  aes(cum_n, cum_species, label = publication_year), 
                  nudge_x = 1500, nudge_y = -10,
                  segment.color = "black") +
  labs(x = "Cumulative number of individuals sampled",
       y = "Cumuluative number of species sampled") + 
  theme_classic(base_size = 14)
rarefaction_plot

```

