---
title: "Albacore Review Phylo Tree"
author: "Natasha Hardy"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/natasha/Documents/POSTDOC/TUNA DIETS/TUNASTATS/data")
```

## Set-up your working environment

```{r working environment}
#Needed to download updated rotl package
remotes::install_github("ropensci/rotl")

# graphics
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(pander)
library(gridExtra)
library(captioner)
library(unmarked)
library(lattice)
library(graphics)

# phylogenetic tools
library(tidyverse)
library(ggtree)
library(ggstance)
library(ape)
library(phylobase)
library(dismo)
library(readxl)
library(rotl) #for phylogenetic analyses, get all the species? from Hinchliff et al. 2015 PNAS
library(phytools)
library(tidyverse)
library(stringr)

```


## Ggtree trials

Using combination of my trial code and Matt Savoca and company's code to build a phylo tree with associated trait and %FO data

```{r load master data}

#data contains sp list, class, order & family although not necessary to have those at the moment.
my_prey = read.csv("/Users/natasha/Documents/POSTDOC/TUNA DIETS/TUNASTATS/data/data_2019/my_prey.csv", header = TRUE) %>%
  dplyr::select(prey_sp, prey_class:prey_family, -X)
str(my_prey) #241 obs. of  5 variables

# A lot of troubleshooting later and I found that the species list needs to go on the far left side of the data, 
# all other data/factors need to be added to the RHS of the species list


```

```{r building basic tree}
# TREE BUILD ----

#Building the basic tree

# Tree build 1 ----
breaks <- c(seq(1,nrow(my_prey),50),nrow(my_prey)+1)  # why are we doing this?
#looking up each of the species in dataset to a phylogeny, doing it by sets of 50
#if there's an NA (species that didn't match a value in known phylogeny), breaks the whole chunk of 50 species

for (i in 1:(length(breaks)-1)){
  taxa <- as.character(my_prey$prey_sp[breaks[i]:(breaks[i+1]-1)])
  taxa <- taxa[taxa != "" & !is.na(taxa)]
  
  resolved_namest <- tnrs_match_names(taxa)                          # I think this is where all the extra species fall out
  resolved_namest <- resolved_namest[!is.na(resolved_namest$unique_name),]  # ignore an NA
  if (i==1){
    resolved_namess <- resolved_namest
  } else {
    resolved_namess <- rbind(resolved_namess, resolved_namest)
  }
}
resolved_names <- resolved_namess
resolved_names <- resolved_names[resolved_names$flags!="INCERTAE_SEDIS_INHERITED",]

# Tree 1 ----
#original tree based on simple taxon datset
my_tree <- tol_induced_subtree(ott_ids = resolved_names$ott_id, label_format = "name")

my_tree$tip.label<-gsub("_"," ",my_tree$tip.label) # removes underscore between genus and species names
my_tree$tip.label<-str_extract(my_tree$tip.label, "[A-Z][a-z]+ [a-z]+")

my_tree <- compute.brlen(my_tree, method = "Grafen", power = 1/2) #add branch lengths to my tree using the Grafen (1989) method
my_tree <- ladderize(my_tree, right = TRUE)

View(my_tree)

## NOTES ----
# A lot of troubleshooting later and I found that the species list needs to go on the far left side of the data, 
# all other data/factors need to be added to the RHS of the species list
# My new tree (with added Class & Family vectors) is skipping one species for some reason and parsing to NA...

# SAVE TREE ----
write.tree(my_tree, "albacore_diet_tree2")
#write.tree(my_tree2, "albacore_diet_tree2")

# Reload tree ----
# Problem with new tree - use old tree?
my_tree <- read.tree("/Users/natasha/Documents/POSTDOC/TUNA DIETS/TUNASTATS/data/data_2019/albacore_diet_tree2")

```

```{r Prep tree to plot}

#checking my_prey data
str(my_tree)
#View(my_tree)
#Edit tip labels
my_tree$tip.label <- as.factor(sub("_", " ", my_tree$tip.label))


# dataframe dimensions issue? ----
# according to Matt's code dataframe dimension should not be an issue when parsing data to tip labels...
# Try dimension solution
#we have a data frame dimension issue when plotting our data values onto the tree
nrow(my_prey) == nrow(my_tree$tip.label) #logical(0) = NO
nrow(my_prey) #241
#nrow(my_tree$tip.label) #233
#Need to fix nrow issue

#This fixes the dimension issue
my_prey2 = my_prey[my_tree$tip.label,] 
#takes the species values that equal the remaining sp that were parsed to the tree
#and just selecting the columns of data
str(my_prey2) #dim = 233 rows, but still recording 239 levels of the factor PreySP
str(my_prey) #dim = 239 rows and 239 levels of PreySP

```


```{r Plotting basic tree}
# Tree plot 1 ----
NH_base <- ggtree(my_tree, layout="fan", open.angle=0) + #can vary width with size=1.5
  #geom_text2(aes(label=label), hjust=-.2, size=4) +
  #geom_tiplab2()+
  ggplot2::xlim(-0.6, 1.3) 
NH_base

```

```{r Plotting better basic tree, width=30, height=30, echo=FALSE,message=FALSE, warning=FALSE}
#improving the base tree

#checking my tip labels are factors, I believe this is important for parsing tree labels to the tree
my_tree$tip.label <- as.factor(my_tree$tip.label)


p %<+% my_prey + 
  geom_tiplab2(aes(label = paste0("italic('", label, "')"), angle = angle), parse = TRUE, align = TRUE, size = 6)

dev.copy2pdf(file="prey_tree_better.pdf", width=30, height=30)

```

```{r More plotting, width=30, height=30, echo=FALSE,message=FALSE, warning=FALSE}

# Adding data
p %<+% my_prey + 
  aes(color = PreyClass) +
  geom_tiplab2(aes(label = paste0("italic('", label, "')"),
                   color=PreyClass, angle = angle), parse = TRUE, 
               align = TRUE, size = 6) #+
  # geom_tiplab2(aes(color=Sp_mean, angle = angle),
  #              align = TRUE, size = 6) +
  # geom_cladelabel()+
  #scale_color_gradientn(colours = c("steelblue4","steelblue3",
  #                                  "coral", "coral1",
  #                                  "firebrick2", "firebrick3", "firebrick4"), 
  #                      name = "average %FO") +
  #theme(legend.position = c(0.5,0.5),
  #      legend.key.size = unit(1.75, "cm"),
  #      legend.text = element_text(size = 18),
  #      legend.title = element_text(size = 20))

#geom_tippoint()
#facet_plot()
#geom_facet() --> add %FO as bar plot that is coloured with

#scenario
#colour species by habitat + tippoint size varies by %FO

dev.copy2pdf(file="preyprelim_phylo_ggtree.pdf", width=30, height=30)
#ggsave("Prelim_phylo_ggtree2.jpg", width = 35, height = 35, units = "in")

# Matt second code
p %<+% my_prey + 
  aes(color = ave_fo) +
  geom_tiplab2(aes(label = paste0("italic('", label, "')"),
                   color=Sp_mean, angle = angle), parse = TRUE,
               size = 6, align = FALSE, hjust = -0.05) +
  geom_tippoint(aes(color = ave_fo, shape = commercial, size = studies_cat)) +
  scale_color_gradientn(colours = c("steelblue4",
                                    "gray40",
                                    "coral", "coral1",
                                    "firebrick2", "firebrick3", "firebrick4"),
                        name = "Proportion with \ningested plastic") +
  #scale_size(range = c(3, 7)) +
  scale_size_continuous(guide = FALSE, range = c(3, 7)) +
  labs(shape = "Commercial \nstatus") +
  theme(legend.position = c(0.5,0.5),
        legend.key.size = unit(2.5, "cm"),
        legend.text = element_text(size = 24),
        legend.title = element_text(size = 26),
        legend.box = "horizontal") +
  guides(shape = guide_legend(override.aes = list(size = 5)))


p + geom_facet(panel = "Trait", data = bar_data, geom = ggstance::geom_barh, 
             aes(x = dummy_bar_value, color = location, fill = location), 
             stat = "identity", width = .6) +
  theme_tree2(legend.position=c(.05, .85))
p



# other options

# first plot try, vertical layout with data ----
p_stand <- ggtree(my_tree) + 
  #geom_text2(aes(label=label), hjust=-.2, size=4) +
  ggplot2::xlim(0, 1.2)
p_stand

# Adding data
p_stand %<+% d_sp_sum +
  aes(color = Sp_mean) +
  geom_tiplab(aes(color=Sp_mean), align = TRUE, size = 3) +
  scale_color_gradientn(colours = c("#053061" ,"#2166AC", "#4393C3", "#F4A582", "#D6604D", "#B2182B", "#67001F"), 
                        name = "Proportion with \nplastic") +
  geom_hilight(node=1, fill="gold") + 
  theme(legend.position = c(0.2,0.8))


p2 <- facet_plot(p_stand, panel = 'Prop w plastic', data = d_sp_sum, 
                 geom = ggstance::geom_barh, 
                 mapping = aes(x = Sp_mean), 
                 stat='identity') 
p2

geom_facet(
  
  inset(my_tree, d_sp_sum$Sp_mean, width=0.2, height=0.15, hjust=-1)
  
  
  legend.title = element_blank(), # no title
  legend.key = element_blank()) # no keys



geom_tippoint(aes(color=order))



geom_tiplab(aes(color = Sp_mean))


p %<+% d + geom_text(aes(color=, label=label), hjust=-0.5)
```

```{r Troubleshoot ongoing issues}
# Need to find node labels so that we can colour the tree and clades

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
